### ISSUE TITLE
Docker images are not being built

### ISSUE THREAD

**Issue by haxorof** [chop-dbhi/prometheus-sql#102]
Seems Docker images are not being built when commit is done on master. Last time it worked was 5 months ago.

@bruth Can you check why it is not built anymore?

**Comment by bruth** [comment]
@haxorof Appears automated builds on Docker Hub now require a paid account.

**Comment by haxorof** [comment]
Aha, I saw it too now when I looked at my own Docker hub account. 

If you would specify the following secrets in the repository settings then it would be possible to build and push via Github Actions. This is what I do in my own repositories since it gives me a bit more control of when to push etc:
- DOCKERHUB_TOKEN
- DOCKERHUB_USERNAME
- DOCKERHUB_PASSWORD

It would then be possible for me to for example add the following in the Github CI and also allow it to push:
```yaml
      - name: Login to DockerHub
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
```
And for updating the description on Docker Hub:
```yaml
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2.4.3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: dbhi/prometheus-sql
```
What do you think @bruth ?
