### ISSUE TITLE
How to connect with SSL?

### ISSUE THREAD

**Issue by alexgesser** [chop-dbhi/prometheus-sql#124]
Hello, everyone.
Started to use with sql-agent. On database server turned on TLS. (It's impossible to turn off on mysql by requirements)
Getting an error:
`[some_query] 503 Service Unavailable: problem connecting to database: Error 3159: Connections using insecure transport are prohibited while --require_secure_transport=ON`
In parameters I didn't find any arguments in settings except `sslmode: disable`. Can you point me please on configuration with SSL enabled?

I tried
`sslmode: enable`
`sslmode: enabled`
`ssl_ca: /path/to/cert.pem`
`ssl_cert: /path/to/cert.pem`
`ssl-ca: /path/to/cert.pem`
`ssl-cert: /path/to/cert.pem` etc.

my basic config:

```
connection:
        host: sql.apples.com
        port: 3306
        user: sql-agent
        password: superpassword
        database: specialdatabase
        #sslmode: enable?
```
