### ISSUE TITLE
Support for defining data sources to be referenced by queries

### ISSUE THREAD

**Issue by yosefy** [chop-dbhi/prometheus-sql#15]
hi
may be you could enable default config for
db connection (per file may be), driver and interval

as sometime we have lots of queries to one db
like a long list
and have to add all those lines each time

thanks

**Comment by haxorof** [comment]
Hi @yosefy 
Let's say it was possible to specify some "enviromental file" which could for example contain this kind of information as in the example below:
```yaml
# Default values
defaults:
  # The time between query execution. This should be set relative to the frequency
  # of expected updates and the required granularity of changes.
  query-interval: 1h

# Data sources which can be referenced in queries.
data-sources:
    - postgres-example:
        driver: postgresql
        connection:
            host: example.org
            port: 5432
            user: postgres
            password: s3cre7
            database: products

    - mysql-example:
        driver: mysql
        connection:
            host: example.org
            port: 3306
            user: root
            password: unsecure
            database: test
```
Then it would be possible to reference these data sources like this in the query files:
```yaml
- num_products:
    data-source: postgres-example
    sql: >
        select count(product_id)
        from product
            inner join product_category
                on (product.category_id = product_category.id)
            inner join product_category_idx
                on (product_category.id = product_category_idx.category_id)
        where product_category_idx.category_id = :category_id
            or product_category_idx.ancestor_category_id = :category_id
    params:
        category_id: 5
```

Is this kind of what you are after?

Cheers!
