### ISSUE TITLE
Query results as metrics

### ISSUE THREAD

**Issue by PrFalken** [chop-dbhi/prometheus-sql#2]
Hello, do you plan on exposing the actual query results as prometheus metrics ?
I would like to use prometheus-sql to export business metric counts from a DB and graph them.

**Comment by bruth** [comment]
Hi, good question. Exposing them at metrics would really depend on the content of the query. I presume it could be a configuration option. How would you expect the results be expressed as metrics? Can you provide an example?

**Comment by PrFalken** [comment]
something like this maybe : 
```
query:
  database: mydb
  sql: >
    SELECT count(*) as user_count FROM users
  interval: 1m
  identifier: user_count
  metric_type: counter
```
would give :
```
# TYPE user_count counter
user_count{database=“mydb”} 4242
```
Since you must have a one number result for prometheus, a request providing anything else than one number in one field would end up in an error.
