### ISSUE TITLE
Simple Counter

### ISSUE THREAD

**Issue by gimler** [chop-dbhi/prometheus-sql#3]
i try to get the exporter to work with grafana.

queries.yml

``` yaml
licenses:
    driver: mysql

    connection:
        host: db
        port: 3306
        user: root
        password: ...
        database: ...

    sql: >
        SELECT count(id) as number
        FROM user
        WHERE active = 'Y'

    identifier: number

    interval: 1h
```

Under `/state/licenses` i get `[{"number":"34"}]`

How can i access this value `number` in grafana?
