### ISSUE TITLE
use nan as error value

### ISSUE THREAD

**Issue by roidelapluie** [chop-dbhi/prometheus-sql#38]
Would be great to be able to set NaN as value when a query fails.

**Comment by haxorof** [comment]
As I see it this is possible today:
```yaml
- nr_companies_per_country:
    value-on-error: NaN
    sql: >
        select country, count(1) as cnt from Companies group by country
    data-field: cnt
```
Endpoint output when Prometheus SQL query fails due to connectivity issues with SQL agent after previously successful queries:
```
# HELP query_result_nr_companies_per_country Result of an SQL query
# TYPE query_result_nr_companies_per_country gauge
query_result_nr_companies_per_country{country="irl"} NaN
query_result_nr_companies_per_country{country="swe"} NaN
query_result_nr_companies_per_country{country="usa"} NaN
```
