### ISSUE TITLE
How do you use '-config prometheus-sql.yml' in docker-compose

### ISSUE THREAD

**Issue by huehnerlady** [chop-dbhi/prometheus-sql#46]
Hi,

we want to use docker-compose to start the docker container. In addition we have a queries file and a config file.

With docker run it all works fine:
```
docker run -d \
  --name prometheus-sql \
  -p 8080:8080 \
  -v ${PWD}/queries.yml:/queries.yml \
  -v ${PWD}/example-config.yml:/prometheus-sql.yml \
  --link sqlagent:sqlagent \
  dbhi/prometheus-sql \
  -service http://sqlagent:5000 \
  -config prometheus-sql.yml
```

If we include the config inside the queries.yml file, we can get the compose to work, but is we want to take the config out, it doesn't and we get the error 
`No data source or driver is specified for query [QUERY_NAME]`

docker-compose file:
```
prometheus-sql:
  container_name: prometheus-sql
  ports:
    - 1080:8080/tcp
  image: dbhi/prometheus-sql
  links:
    - sqlagent
  volumes:
    - ${PWD}/example-config.yml:/prometheus-sql.yml
    - ${PWD}/queries.yml:/queries.yml
```
We assume that the property `-config prometheus-sql.yml` is important to enable the config file, but we could not fin a way to set this property in docker-compose. 

Could you maybe help there?

**Comment by bruth** [comment]
Hi @huehnerlady. With docker-compose you can specify [the command to run](https://docs.docker.com/compose/compose-file/#command). [The Dockerfile](https://github.com/chop-dbhi/prometheus-sql/blob/master/Dockerfile#L16) defines the default command (referencing SQL Agent), so you can override this like so:

```yaml
prometheus-sql:
  container_name: prometheus-sql
  ports:
    - 1080:8080/tcp
  image: dbhi/prometheus-sql
  links:
    - sqlagent
  command: >
    -service http://sqlagent:5000
    -config /prometheus-sql.yml
  volumes:
    - ${PWD}/example-config.yml:/prometheus-sql.yml
    - ${PWD}/queries.yml:/queries.yml
```
