### ISSUE TITLE
Transaction processing times

### ISSUE THREAD

**Issue by PaulWalkerUK** [chop-dbhi/prometheus-sql#9]
I've got a table that records certain business transaction details. One thing I'd like to do is to have a graph in Grafana showing things like the number of transactions and how long they take.

For example, let's say my table looks something like this:

```SQL
CREATE TABLE business_trans (
    trans_id    NUMBER,
    trans_start DATE,
    trans_end   DATE
);
```

If I just subtract the dates, that would give me the processing time for each transaction, but then what? Do I need to do all the aggregation in my SELECT statement (eg find the average over the last 2 minutes then just run that query every 1 minute for example)?

What about the number of transactions? I can just count the table, but then how do I get Prometheus to diff the numbers to give "trans/per minute" etc?

Apologies if this should be obvious, I'm pretty new to Prometheus!

**Comment by haxorof** [comment]
Hi @PaulWalkerUK 

Not sure if this answers your question but if you got a table as you described above then you could create a `queries.yml` which could looks similar to this:

```yaml
- transaction_total:
    driver: mysql
    connection:
        host: mysql
        port: 3306
        user: root
        password: unsecure
        database: test
    sql: >
        select count(1) trans_count from test.business_trans
    interval: 5s
    data-field: trans_count
- transaction_avg:
    driver: mysql
    connection:
        host: mysql
        port: 3306
        user: root
        password: unsecure
        database: test
    sql: >
         select avg(trans_end - trans_start) AS trans_avg, '1min' AS span from test.business_trans
            where trans_end is not null and trans_end between adddate(CURRENT_TIMESTAMP, INTERVAL -1 MINUTE) and CURRENT_TIMESTAMP;
    interval: 5s
    data-field: trans_avg
```
This will then produce the following output on the /metrics endpoint:
```
# HELP query_result_transaction_avg Result of an SQL query
# TYPE query_result_transaction_avg gauge
query_result_transaction_avg{span="1min"} 0
# HELP query_result_transaction_total Result of an SQL query
# TYPE query_result_transaction_total gauge
query_result_transaction_total 9
```
Metric `query_result_transaction_avg` will show the average transaction time for the transactions which ended within the last minute.

If you want to get number of transations per second in Prometheus then you just write the query like this:
```
rate(query_result_transaction_total[5min])
```

Hope it will answer your questions!
